# Generated by Django 5.2 on 2025-05-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
